export const GET_CARTOONS = "GET_CARTOONS/LOAD";
export const GET_CARTOONS_SUCCESS = "GET_CARTOONS/LOAD_SUCCESS";
export const GET_CARTOONS_FAIL = "GET_CARTOONS/LOAD_FAIL";
export const GET_CARTOONS_URL = "/api/Cartoons";

export const POST_CARTOON_LIKES = "POST_CARTOON_LIKES/LOAD";
export const POST_CARTOON_LIKES_SUCCESS = "POST_CARTOON_LIKES/LOAD_SUCCESS";
export const POST_CARTOON_LIKES_FAIL = "POST_CARTOON_LIKES/LOAD_FAIL";
export const POST_CARTOON_LIKES_URL = "/api/CartoonLikes";

export const GET_MY_CARTOON_LIKES = "GET_MY_CARTOON_LIKES/LOAD";
export const GET_MY_CARTOON_LIKES_SUCCESS = "GET_MY_CARTOON_LIKES/LOAD_SUCCESS";
export const GET_MY_CARTOON_LIKES_FAIL = "GET_MY_CARTOON_LIKES/LOAD_FAIL";
export const GET_MY_CARTOON_LIKES_URL = "/api/CartoonLikes";

export const GET_CARTOON_GALLERY = "GET_CARTOON_GALLERY/LOAD";
export const GET_CARTOON_GALLERY_SUCCESS = "GET_CARTOON_GALLERY/LOAD_SUCCESS";
export const GET_CARTOON_GALLERY_FAIL = "GET_CARTOON_GALLERY/LOAD_FAIL";
export const GET_CARTOON_GALLERY_URL = "/api/Cartoons/GetCartoonGallery";
