export const GET_CARTOONS = "GET_CARTOONS/LOAD";
export const GET_CARTOONS_SUCCESS = "GET_CARTOONS/LOAD_SUCCESS";
export const GET_CARTOONS_FAIL = "GET_CARTOONS/LOAD_FAIL";
export const GET_CARTOONS_URL = "/api/Cartoons";

export const POST_CARTOON_LIKES = "POST_CARTOON_LIKES/LOAD";
export const POST_CARTOON_LIKES_SUCCESS = "POST_CARTOON_LIKES/LOAD_SUCCESS";
export const POST_CARTOON_LIKES_FAIL = "POST_CARTOON_LIKES/LOAD_FAIL";
export const POST_CARTOON_LIKES_URL = "/api/CartoonLikes";
