export const POST_NOTIFICATION_TOKEN = "POST_NOTIFICATION_TOKEN/LOAD";
export const POST_NOTIFICATION_TOKEN_SUCCESS =
  "POST_NOTIFICATION_TOKEN/LOAD_SUCCESS";
export const POST_NOTIFICATION_TOKEN_FAIL = "POST_NOTIFICATION_TOKEN/LOAD_FAIL";
export const POST_NOTIFICATION_TOKEN_URL = "/api/NotificationTokens";
