export const GET_PROJECT_DETAIL = "GET_PROJECT_DETAIL/LOAD";
export const GET_PROJECT_DETAIL_SUCCESS = "GET_PROJECT_DETAIL/LOAD_SUCCESS";
export const GET_PROJECT_DETAIL_FAIL = "GET_PROJECT_DETAIL/LOAD_FAIL";
export const GET_PROJECT_DETAIL_URL = "/api/Settings/GetProjectDetail";
